name: deeplearning_app_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchaudio
  - pillow
  - scipy
  - requests
  - fastapi
  - uvicorn
  - pip:
      - easyocr
      - transformers