name: ocr_translation_tts_env
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pillow
  - scipy
  - pytorch::pytorch
  - pytorch::torchaudio
  - requests
  - jupyter
  - pip:
      - easyocr
      - transformers
      - sentencepiece
      - fastapi
      - uvicorn
     